server:
  port: 80
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/barbecue
    username: sa
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: h2
  h2:
    console:
      enabled: true
      path: /h2-console
